CREATE TABLE medico (
id bigint generated by default as identity,
id_agenda bigint,
crm varchar(9) not null,
contact varchar(11),
name varchar(150),
especialidade varchar(255) check (especialidade in ('CARDIOLOGIA','DERMATOLOGIA','GINECOLOGIA','ORTOPEDIA','PEDIATRIA','NEUROLOGIA','ONCOLOGIA','PSIQUIATRIA','ENDOCRINOLOGIA','GASTROENTEROLOGIA','OTORRINOLARINGOLOGIA','UROLOGIA','REUMATOLOGIA','HEMATOLOGIA','NEFROLOGIA','ANESTESIOLOGIA','NEONATOLOGIA')),
 primary key (id)
)