CREATE TABLE exame(
id bigint generated by default as identity,
id_consulta bigint,
crm_medico varchar(9) not null,
cpf_paciente varchar(11) not null,
conteudo varchar(255),
nome_medico varchar(255),
nome_paciente varchar(255),
primary key (id)
)